/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pertemuan5.joptionpane;

import javax.swing.JOptionPane;

/**
 *
 * @author D-8
 */
public class jOption extends javax.swing.JFrame {

    /**
     * Creates new form jOption
     */
    String nama;
    int answer;

    public jOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_massage_dialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_plain = new javax.swing.JButton();
        btn_input_dialog = new javax.swing.JButton();
        btn_konfirmasi = new javax.swing.JButton();
        btn_pilihan = new javax.swing.JButton();
        btn_error = new javax.swing.JButton();
        btn_information = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_question = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_massage_dialog.setText("Massage Dialog");
        btn_massage_dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_massage_dialogActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("JOption Pane");

        btn_plain.setText("Plain Massage");
        btn_plain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plainActionPerformed(evt);
            }
        });

        btn_input_dialog.setText("Input Dialog");
        btn_input_dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_input_dialogActionPerformed(evt);
            }
        });

        btn_konfirmasi.setText("Dialog Konfirmasi");
        btn_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfirmasiActionPerformed(evt);
            }
        });

        btn_pilihan.setText("Dialog Pilihan");
        btn_pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihanActionPerformed(evt);
            }
        });

        btn_error.setText("Error Massage");
        btn_error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_errorActionPerformed(evt);
            }
        });

        btn_information.setText("Information Massage ");
        btn_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_informationActionPerformed(evt);
            }
        });

        jButton1.setText("Warning Massage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_question.setText("Qustion Massage");
        btn_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_questionActionPerformed(evt);
            }
        });

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btn_plain))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(btn_massage_dialog))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_error)
                                    .addComponent(btn_konfirmasi)
                                    .addComponent(jButton1))))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pilihan)
                            .addComponent(btn_input_dialog)
                            .addComponent(btn_information)
                            .addComponent(btn_question)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btn_close)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(btn_plain)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_massage_dialog)
                    .addComponent(btn_input_dialog))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_konfirmasi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_pilihan)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_error)
                    .addComponent(btn_information))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_question))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_massage_dialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_massage_dialogActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "ini adalah pesanku");
    }//GEN-LAST:event_btn_massage_dialogActionPerformed

    private void btn_plainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plainActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Welcome in this program", "Pesan Plain", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btn_plainActionPerformed

    private void btn_input_dialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_input_dialogActionPerformed
        // TODO add your handling code here:
        nama = JOptionPane.showInputDialog(this, "Masukkan nama kamu ");

        JOptionPane.showMessageDialog(this, "Hallo Aku " + nama);
    }//GEN-LAST:event_btn_input_dialogActionPerformed

    private void btn_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfirmasiActionPerformed
        // TODO add your handling code here:
        answer = JOptionPane.showConfirmDialog(this, "Silahkan konfirmasi");

        switch (answer) {
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(this, "Iya");
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(this, "tidak");
                break;
            case JOptionPane.CANCEL_OPTION:
                JOptionPane.showMessageDialog(this, "cancel");
                break;
            default:
                throw new AssertionError("masukan inputan yang benar");
        }
    }//GEN-LAST:event_btn_konfirmasiActionPerformed

    private void btn_pilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihanActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showOptionDialog(this, "ingin keluar?", "keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (answer == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "program keluar");
            System.exit(0);
        }
    }//GEN-LAST:event_btn_pilihanActionPerformed

    private void btn_errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_errorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Program tidak bisa berjalan", "Error!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_errorActionPerformed

    private void btn_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_informationActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Masukkan data yang valid", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_informationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Data belum lengkap!", "Warning!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_questionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Apakah yakin ingin lanjut?", "Question", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btn_questionActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_error;
    private javax.swing.JButton btn_information;
    private javax.swing.JButton btn_input_dialog;
    private javax.swing.JButton btn_konfirmasi;
    private javax.swing.JButton btn_massage_dialog;
    private javax.swing.JButton btn_pilihan;
    private javax.swing.JButton btn_plain;
    private javax.swing.JButton btn_question;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
